INSERT INTO ORGN(ORGN_NO, ORGN_ID, ORGN_NM, ORGN_DSC) VALUES(1, 'ORGN-0100101', '연구소/ICM팀', '부서설명...');
INSERT INTO ORGN(ORGN_NO, ORGN_ID, ORGN_NM, ORGN_DSC) VALUES(2, 'ORGN-0100102', '연구소/TM팀', '부서설명...');
INSERT INTO ORGN(ORGN_NO, ORGN_ID, ORGN_NM, ORGN_DSC) VALUES(3, 'ORGN-0100102', '연구소/SG팀', '부서설명...');


INSERT INTO ATHRZTN(ATHRZTN_NO, ATHRZTN_NM, ATHRZTN_DSC, FIRST_RGST_TM) VALUES(1, '보안관리자', '권한설명...', CURRENT_TIMESTAMP());
INSERT INTO ATHRZTN(ATHRZTN_NO, ATHRZTN_NM, ATHRZTN_DSC, FIRST_RGST_TM) VALUES(2, '모니터링', '권한설명...', CURRENT_TIMESTAMP());
INSERT INTO ATHRZTN(ATHRZTN_NO, ATHRZTN_NM, ATHRZTN_DSC, FIRST_RGST_TM) VALUES(3, '운영자', '권한설명...', CURRENT_TIMESTAMP());
